In [1]:
import os
##see if you can parameterize the file name
os.chdir('/Users/lilchainey/Dropbox/PostDoc/SpatialPhylo/ProjectFiles/MetrosiderosShapes')

In [2]:
import pandas as pd

In [3]:
#Read in species dataframe ##Change this to remove select only specific columns from original downloaded occurence sheet
metrosideros = pd.read_csv("occ.csv",index_col="genus")
metrosideros

,kingdom,phylum,order,family,specificEpithet,infraspecificEpithet,decimalLatitude,decimalLongitude
genus,,,,,,,,
Metrosideros,Plantae,Magnoliophyta,Myrtales,Myrtaceae,kermadecensis,NaN,20.756900,-156.321000
Metrosideros,Plantae,Magnoliophyta,Myrtales,Myrtaceae,kermadecensis,NaN,20.756900,-156.321000
Metrosideros,Plantae,Magnoliophyta,Myrtales,Myrtaceae,macropus,NaN,21.600000,-157.900000
Metrosideros,Plantae,Magnoliophyta,Myrtales,Myrtaceae,macropus,NaN,21.533125,-157.925278
Metrosideros,Plantae,Magnoliophyta,Myrtales,Myrtaceae,macropus,NaN,21.413333,-157.866944
...,...,...,...,...,...,...,...,...
Metrosideros,Plantae,Magnoliophyta,Myrtales,Myrtaceae,waialealae,NaN,22.165752,-159.595664
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,waialealae,NaN,21.968950,-159.495682
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,waialealae,NaN,22.165752,-159.595664
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,waialealae,NaN,22.165752,-159.595664
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,waialealae,NaN,21.961830,-159.491300

In [4]:
#Remove all entries with subspecies data to subset the original dataframe
metrosideros['infraspecificEpithet'] = metrosideros['infraspecificEpithet'].fillna('none')
metrosideros_og = metrosideros[metrosideros['infraspecificEpithet'] != 'none']
display(metrosideros_og)

,kingdom,phylum,order,family,specificEpithet,infraspecificEpithet,decimalLatitude,decimalLongitude
genus,,,,,,,,
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,polymorpha,var. dieteri,22.148611,-159.625556
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,polymorpha,var. dieteri,22.148333,-159.625556
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,polymorpha,var. dieteri,22.148333,-159.625556
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,polymorpha,var. dieteri,22.148333,-159.625556
Metrosideros,Plantae,Magnoliophyta,Myrtales,Myrtaceae,polymorpha,var. dieteri,22.000000,-160.000000
...,...,...,...,...,...,...,...,...
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,waialealae,var. waialealae,22.072380,-159.508698
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,waialealae,var. waialealae,22.131684,-159.524803
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,waialealae,var. waialealae,22.006574,-159.500160
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,waialealae,var. waialealae,22.081731,-159.496634
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,waialealae,var. waialealae,22.005199,-159.499970

In [5]:
#Disable error for SettingWithCopyWarning before merging column contents
import pandas as pd
pd.options.mode.chained_assignment = None

#Merge species/subsp. names
metrosideros_og["species"] = metrosideros_og["specificEpithet"] + ' ' + metrosideros_og["infraspecificEpithet"]
metrosideros_og

,kingdom,phylum,order,family,specificEpithet,infraspecificEpithet,decimalLatitude,decimalLongitude,species
genus,,,,,,,,,
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,polymorpha,var. dieteri,22.148611,-159.625556,polymorpha var. dieteri
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,polymorpha,var. dieteri,22.148333,-159.625556,polymorpha var. dieteri
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,polymorpha,var. dieteri,22.148333,-159.625556,polymorpha var. dieteri
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,polymorpha,var. dieteri,22.148333,-159.625556,polymorpha var. dieteri
Metrosideros,Plantae,Magnoliophyta,Myrtales,Myrtaceae,polymorpha,var. dieteri,22.000000,-160.000000,polymorpha var. dieteri
...,...,...,...,...,...,...,...,...,...
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,waialealae,var. waialealae,22.072380,-159.508698,waialealae var. waialealae
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,waialealae,var. waialealae,22.131684,-159.524803,waialealae var. waialealae
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,waialealae,var. waialealae,22.006574,-159.500160,waialealae var. waialealae
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,waialealae,var. waialealae,22.081731,-159.496634,waialealae var. waialealae
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,waialealae,var. waialealae,22.005199,-159.499970,waialealae var. waialealae

In [6]:
#delete individual species/subspecies columns
metrosideros_og = metrosideros_og.drop(['specificEpithet','infraspecificEpithet'],axis=1)
metrosideros_og

,kingdom,phylum,order,family,decimalLatitude,decimalLongitude,species
genus,,,,,,,
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,22.148611,-159.625556,polymorpha var. dieteri
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,22.148333,-159.625556,polymorpha var. dieteri
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,22.148333,-159.625556,polymorpha var. dieteri
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,22.148333,-159.625556,polymorpha var. dieteri
Metrosideros,Plantae,Magnoliophyta,Myrtales,Myrtaceae,22.000000,-160.000000,polymorpha var. dieteri
...,...,...,...,...,...,...,...
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,22.072380,-159.508698,waialealae var. waialealae
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,22.131684,-159.524803,waialealae var. waialealae
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,22.006574,-159.500160,waialealae var. waialealae
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,22.081731,-159.496634,waialealae var. waialealae
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,22.005199,-159.499970,waialealae var. waialealae

In [7]:
#Remove all entries withOUT subspecies data to subset the original dataframe
metrosideros_nosub = metrosideros[~metrosideros.infraspecificEpithet.str.contains("var")]

#change column name to match new species column in the subspecies table
metrosideros_nosub.rename(columns={'specificEpithet':'species'}, inplace=True)
metrosideros_nosub

,kingdom,phylum,order,family,species,infraspecificEpithet,decimalLatitude,decimalLongitude
genus,,,,,,,,
Metrosideros,Plantae,Magnoliophyta,Myrtales,Myrtaceae,kermadecensis,none,20.756900,-156.321000
Metrosideros,Plantae,Magnoliophyta,Myrtales,Myrtaceae,kermadecensis,none,20.756900,-156.321000
Metrosideros,Plantae,Magnoliophyta,Myrtales,Myrtaceae,macropus,none,21.600000,-157.900000
Metrosideros,Plantae,Magnoliophyta,Myrtales,Myrtaceae,macropus,none,21.533125,-157.925278
Metrosideros,Plantae,Magnoliophyta,Myrtales,Myrtaceae,macropus,none,21.413333,-157.866944
...,...,...,...,...,...,...,...,...
Metrosideros,Plantae,Magnoliophyta,Myrtales,Myrtaceae,waialealae,none,22.165752,-159.595664
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,waialealae,none,21.968950,-159.495682
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,waialealae,none,22.165752,-159.595664
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,waialealae,none,22.165752,-159.595664
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,waialealae,none,21.961830,-159.491300

In [8]:
#delete extraneous column with 'none'
metrosideros_nosub = metrosideros_nosub.drop(['infraspecificEpithet'],axis=1)
metrosideros_nosub

,kingdom,phylum,order,family,species,decimalLatitude,decimalLongitude
genus,,,,,,,
Metrosideros,Plantae,Magnoliophyta,Myrtales,Myrtaceae,kermadecensis,20.756900,-156.321000
Metrosideros,Plantae,Magnoliophyta,Myrtales,Myrtaceae,kermadecensis,20.756900,-156.321000
Metrosideros,Plantae,Magnoliophyta,Myrtales,Myrtaceae,macropus,21.600000,-157.900000
Metrosideros,Plantae,Magnoliophyta,Myrtales,Myrtaceae,macropus,21.533125,-157.925278
Metrosideros,Plantae,Magnoliophyta,Myrtales,Myrtaceae,macropus,21.413333,-157.866944
...,...,...,...,...,...,...,...
Metrosideros,Plantae,Magnoliophyta,Myrtales,Myrtaceae,waialealae,22.165752,-159.595664
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,waialealae,21.968950,-159.495682
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,waialealae,22.165752,-159.595664
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,waialealae,22.165752,-159.595664
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,waialealae,21.961830,-159.491300

In [9]:
#concatenate the 
NewTable = pd.concat([metrosideros_nosub, metrosideros_og])
NewTable

,kingdom,phylum,order,family,species,decimalLatitude,decimalLongitude
genus,,,,,,,
Metrosideros,Plantae,Magnoliophyta,Myrtales,Myrtaceae,kermadecensis,20.756900,-156.321000
Metrosideros,Plantae,Magnoliophyta,Myrtales,Myrtaceae,kermadecensis,20.756900,-156.321000
Metrosideros,Plantae,Magnoliophyta,Myrtales,Myrtaceae,macropus,21.600000,-157.900000
Metrosideros,Plantae,Magnoliophyta,Myrtales,Myrtaceae,macropus,21.533125,-157.925278
Metrosideros,Plantae,Magnoliophyta,Myrtales,Myrtaceae,macropus,21.413333,-157.866944
...,...,...,...,...,...,...,...
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,waialealae var. waialealae,22.072380,-159.508698
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,waialealae var. waialealae,22.131684,-159.524803
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,waialealae var. waialealae,22.006574,-159.500160
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,waialealae var. waialealae,22.081731,-159.496634
Metrosideros,Plantae,Magnoliophyta,Myrtales,MYRTACEAE,waialealae var. waialealae,22.005199,-159.499970

In [10]:
LatTable = NewTable.groupby(['species']).agg({'decimalLatitude': ['min', 'max']})
LatTable

                            decimalLatitude
                                        min        max
species
kermadecensis                     20.756900  20.756900
macropus                          21.413300  21.600000
polymorpha                       -22.217500  22.228683
polymorpha var. dieteri           22.000000  22.198353
polymorpha var. glaberrima        19.083300  22.218333
polymorpha var. incana            19.016700  21.600000
polymorpha var. macrophylla      -19.708400  20.903100
polymorpha var. newellii          19.683300  20.100000
polymorpha var. polymorpha        19.150000  22.166667
polymorpha var. pumila            20.090700  22.150833
rugosa                            21.050000  21.600000
tremuloides                       21.210000  21.502222
waialealae                        21.961830  22.165752
waialealae var. fauriei           20.972729  21.345600
waialealae var. waialealae        21.980000  22.152500

In [11]:
LonTable = NewTable.groupby('species').agg({'decimalLongitude': ['min', 'max']})
LonTable

                            decimalLongitude
                                         min         max
species
kermadecensis                    -156.321000 -156.321000
macropus                         -157.925278 -157.855000
polymorpha                       -159.670000 -155.200000
polymorpha var. dieteri          -160.000000 -159.490000
polymorpha var. glaberrima       -160.000000 -155.000000
polymorpha var. incana           -158.161111 -154.850000
polymorpha var. macrophylla      -156.592000 -155.000000
polymorpha var. newellii         -155.700000 -155.050000
polymorpha var. polymorpha       -159.666667 -154.867000
polymorpha var. pumila           -160.000000 -155.693000
rugosa                           -158.145000  -15.033300
tremuloides                      -158.156111 -157.490000
waialealae                       -159.623056 -159.491300
waialealae var. fauriei          -157.162000 -156.619141
waialealae var. waialealae       -160.000000 -159.492981

In [12]:
#merge the aggragated dataframes by species
combined = pd.concat([LatTable, LonTable]).groupby('species').sum()
combined.insert(0, 'Genus', 'Metrosideros')
combined

                                    Genus decimalLatitude             \
                                                      min        max
species
kermadecensis                Metrosideros       20.756900  20.756900
macropus                     Metrosideros       21.413300  21.600000
polymorpha                   Metrosideros      -22.217500  22.228683
polymorpha var. dieteri      Metrosideros       22.000000  22.198353
polymorpha var. glaberrima   Metrosideros       19.083300  22.218333
polymorpha var. incana       Metrosideros       19.016700  21.600000
polymorpha var. macrophylla  Metrosideros      -19.708400  20.903100
polymorpha var. newellii     Metrosideros       19.683300  20.100000
polymorpha var. polymorpha   Metrosideros       19.150000  22.166667
polymorpha var. pumila       Metrosideros       20.090700  22.150833
rugosa                       Metrosideros       21.050000  21.600000
tremuloides                  Metrosideros       21.210000  21.502222
waialealae                   Metrosideros       21.961830  22.165752
waialealae var. fauriei      Metrosideros       20.972729  21.345600
waialealae var. waialealae   Metrosideros       21.980000  22.152500

                            decimalLongitude
                                         min         max
species
kermadecensis                    -156.321000 -156.321000
macropus                         -157.925278 -157.855000
polymorpha                       -159.670000 -155.200000
polymorpha var. dieteri          -160.000000 -159.490000
polymorpha var. glaberrima       -160.000000 -155.000000
polymorpha var. incana           -158.161111 -154.850000
polymorpha var. macrophylla      -156.592000 -155.000000
polymorpha var. newellii         -155.700000 -155.050000
polymorpha var. polymorpha       -159.666667 -154.867000
polymorpha var. pumila           -160.000000 -155.693000
rugosa                           -158.145000  -15.033300
tremuloides                      -158.156111 -157.490000
waialealae                       -159.623056 -159.491300
waialealae var. fauriei          -157.162000 -156.619141
waialealae var. waialealae       -160.000000 -159.492981

In [13]:
combined.reset_index(inplace=True)
combined.set_index('Genus',inplace=True)
combined

                                  species decimalLatitude             \
                                                      min        max
Genus
Metrosideros                kermadecensis       20.756900  20.756900
Metrosideros                     macropus       21.413300  21.600000
Metrosideros                   polymorpha      -22.217500  22.228683
Metrosideros      polymorpha var. dieteri       22.000000  22.198353
Metrosideros   polymorpha var. glaberrima       19.083300  22.218333
Metrosideros       polymorpha var. incana       19.016700  21.600000
Metrosideros  polymorpha var. macrophylla      -19.708400  20.903100
Metrosideros     polymorpha var. newellii       19.683300  20.100000
Metrosideros   polymorpha var. polymorpha       19.150000  22.166667
Metrosideros       polymorpha var. pumila       20.090700  22.150833
Metrosideros                       rugosa       21.050000  21.600000
Metrosideros                  tremuloides       21.210000  21.502222
Metrosideros                   waialealae       21.961830  22.165752
Metrosideros      waialealae var. fauriei       20.972729  21.345600
Metrosideros   waialealae var. waialealae       21.980000  22.152500

             decimalLongitude
                          min         max
Genus
Metrosideros      -156.321000 -156.321000
Metrosideros      -157.925278 -157.855000
Metrosideros      -159.670000 -155.200000
Metrosideros      -160.000000 -159.490000
Metrosideros      -160.000000 -155.000000
Metrosideros      -158.161111 -154.850000
Metrosideros      -156.592000 -155.000000
Metrosideros      -155.700000 -155.050000
Metrosideros      -159.666667 -154.867000
Metrosideros      -160.000000 -155.693000
Metrosideros      -158.145000  -15.033300
Metrosideros      -158.156111 -157.490000
Metrosideros      -159.623056 -159.491300
Metrosideros      -157.162000 -156.619141
Metrosideros      -160.000000 -159.492981

In [19]:
#combined.to_csv('/Users/lilchainey/Dropbox/PostDoc/SpatialPhylo/ProjectFiles/MetrosiderosShapes/metrosideros.csv')